In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [2]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [3]:
concrete_data_columns = concrete_data.columns

In [4]:
X = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
Y = concrete_data['Strength'] # Strength column

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X, Y, test_size = 0.3)

In [6]:
X.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000

In [7]:
X_train.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
count,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000
mean,279.856449,73.409431,53.747434,182.160472,6.000000,974.543689,771.443828,46.994452
std,103.448423,85.539719,64.064363,21.533824,5.722024,77.247801,79.270853,65.297481
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000
25%,192.000000,0.000000,0.000000,164.900000,0.000000,932.000000,728.000000,7.000000
50%,273.000000,22.000000,0.000000,185.700000,6.500000,968.000000,779.300000,28.000000
75%,349.000000,143.000000,118.300000,193.000000,10.100000,1031.000000,821.000000,56.000000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1134.300000,992.600000,365.000000

In [8]:
predictors_train_norm = ((X_train - X_train.mean())/X_train.std())
predictors_test_norm = ((X_test - X_test.mean())/X_test.std())

In [9]:
target_train_norm = ((Y_train - Y_train.mean())/Y_train.std())
target_test_norm = ((Y_test - Y_test.mean())/Y_test.std())

In [10]:
n_cols = predictors_train_norm.shape[1]

In [11]:
n_cols

8

In [12]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import tensorflow as tf

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [17]:
def regression_model():
    model =keras.Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model
model = regression_model()
model.fit(predictors_train_norm, target_train_norm, validation_split=0.3, epochs =100, verbose=1) #now changing the epoch to 100 for partC

Train on 504 samples, validate on 217 samples
Epoch 1/100
504/504 [==============================] - 1s 3ms/step - loss: 1.3803 - val_loss: 1.4766
Epoch 2/100
504/504 [==============================] - 2s 3ms/step - loss: 1.1493 - val_loss: 1.2402
Epoch 3/100
504/504 [==============================] - 1s 1ms/step - loss: 0.9800 - val_loss: 1.0673
Epoch 4/100
504/504 [==============================] - 0s 959us/step - loss: 0.8657 - val_loss: 0.9392
Epoch 5/100
504/504 [==============================] - 0s 866us/step - loss: 0.7827 - val_loss: 0.8472
Epoch 6/100
504/504 [==============================] - 0s 870us/step - loss: 0.7219 - val_loss: 0.7800
Epoch 7/100
504/504 [==============================] - 0s 758us/step - loss: 0.6789 - val_loss: 0.7235
Epoch 8/100
504/504 [==============================] - 0s 713us/step - loss: 0.6416 - val_loss: 0.6808
Epoch 9/100
504/504 [==============================] - 0s 747us/step - loss: 0.6129 - val_loss: 0.6448
Epoch 10/100
504/504 [==============================] - 0s 789us/step - loss: 0.5874 - val_loss: 0.6162
Epoch 11/100
504/504 [==============================] - 0s 872us/step - loss: 0.5659 - val_loss: 0.5913
Epoch 12/100
504/504 [==============================] - 0s 909us/step - loss: 0.5492 - val_loss: 0.5673
Epoch 13/100
504/504 [==============================] - 0s 828us/step - loss: 0.5321 - val_loss: 0.5501
Epoch 14/100
504/504 [==============================] - 0s 791us/step - loss: 0.5183 - val_loss: 0.5343
Epoch 15/100
504/504 [==============================] - 1s 1ms/step - loss: 0.5061 - val_loss: 0.5209
Epoch 16/100
504/504 [==============================] - 1s 1ms/step - loss: 0.4953 - val_loss: 0.5103
Epoch 17/100
504/504 [==============================] - 1s 998us/step - loss: 0.4859 - val_loss: 0.4993
Epoch 18/100
504/504 [==============================] - 0s 786us/step - loss: 0.4778 - val_loss: 0.4903
Epoch 19/100
504/504 [==============================] - 0s 873us/step - loss: 0.4701 - val_loss: 0.4844
Epoch 20/100
504/504 [==============================] - 0s 917us/step - loss: 0.4634 - val_loss: 0.4768
Epoch 21/100
504/504 [==============================] - 1s 1ms/step - loss: 0.4571 - val_loss: 0.4709
Epoch 22/100
504/504 [==============================] - 1s 996us/step - loss: 0.4508 - val_loss: 0.4647
Epoch 23/100
504/504 [==============================] - 0s 872us/step - loss: 0.4458 - val_loss: 0.4591
Epoch 24/100
504/504 [==============================] - 1s 1ms/step - loss: 0.4406 - val_loss: 0.4537
Epoch 25/100
504/504 [==============================] - 0s 909us/step - loss: 0.4357 - val_loss: 0.4503
Epoch 26/100
504/504 [==============================] - 0s 952us/step - loss: 0.4308 - val_loss: 0.4455
Epoch 27/100
504/504 [==============================] - 0s 757us/step - loss: 0.4265 - val_loss: 0.4405
Epoch 28/100
504/504 [==============================] - 0s 958us/step - loss: 0.4218 - val_loss: 0.4381
Epoch 29/100
504/504 [==============================] - 0s 954us/step - loss: 0.4180 - val_loss: 0.4334
Epoch 30/100
504/504 [==============================] - 0s 988us/step - loss: 0.4134 - val_loss: 0.4303
Epoch 31/100
504/504 [==============================] - 1s 1ms/step - loss: 0.4105 - val_loss: 0.4255
Epoch 32/100
504/504 [==============================] - 0s 664us/step - loss: 0.4066 - val_loss: 0.4241
Epoch 33/100
504/504 [==============================] - 1s 1ms/step - loss: 0.4028 - val_loss: 0.4195
Epoch 34/100
504/504 [==============================] - 1s 1ms/step - loss: 0.3980 - val_loss: 0.4158
Epoch 35/100
504/504 [==============================] - 0s 792us/step - loss: 0.3951 - val_loss: 0.4130
Epoch 36/100
504/504 [==============================] - 0s 674us/step - loss: 0.3913 - val_loss: 0.4091
Epoch 37/100
504/504 [==============================] - 0s 787us/step - loss: 0.3871 - val_loss: 0.4056
Epoch 38/100
504/504 [==============================] - 0s 989us/step - loss: 0.3831 - val_loss: 0.4031
Epoch 39/100
504/504 [==============================] - 0s 908us/step - loss: 0.3789 - val_loss: 0.3988
Epoch 40/100
504/504 [==============================] - 1s 997us/step - loss: 0.3750 - val_loss: 0.3955
Epoch 41/100
504/504 [==============================] - 1s 1ms/step - loss: 0.3715 - val_loss: 0.3913
Epoch 42/100
504/504 [==============================] - 1s 1ms/step - loss: 0.3675 - val_loss: 0.3882
Epoch 43/100
504/504 [==============================] - 0s 675us/step - loss: 0.3642 - val_loss: 0.3854
Epoch 44/100
504/504 [==============================] - 0s 988us/step - loss: 0.3604 - val_loss: 0.3816
Epoch 45/100
504/504 [==============================] - 1s 1ms/step - loss: 0.3569 - val_loss: 0.3778
Epoch 46/100
504/504 [==============================] - 0s 954us/step - loss: 0.3532 - val_loss: 0.3734
Epoch 47/100
504/504 [==============================] - 0s 786us/step - loss: 0.3497 - val_loss: 0.3702
Epoch 48/100
504/504 [==============================] - 1s 1ms/step - loss: 0.3461 - val_loss: 0.3664
Epoch 49/100
504/504 [==============================] - 0s 844us/step - loss: 0.3424 - val_loss: 0.3627
Epoch 50/100
504/504 [==============================] - 0s 913us/step - loss: 0.3389 - val_loss: 0.3593
Epoch 51/100
504/504 [==============================] - 0s 951us/step - loss: 0.3363 - val_loss: 0.3571
Epoch 52/100
504/504 [==============================] - 0s 833us/step - loss: 0.3316 - val_loss: 0.3529
Epoch 53/100
504/504 [==============================] - 0s 951us/step - loss: 0.3275 - val_loss: 0.3495
Epoch 54/100
504/504 [==============================] - 1s 1ms/step - loss: 0.3238 - val_loss: 0.3454
Epoch 55/100
504/504 [==============================] - 0s 838us/step - loss: 0.3196 - val_loss: 0.3413
Epoch 56/100
504/504 [==============================] - 0s 361us/step - loss: 0.3158 - val_loss: 0.3380
Epoch 57/100
504/504 [==============================] - 0s 360us/step - loss: 0.3120 - val_loss: 0.3336
Epoch 58/100
504/504 [==============================] - 0s 390us/step - loss: 0.3086 - val_loss: 0.3299
Epoch 59/100
504/504 [==============================] - 0s 473us/step - loss: 0.3052 - val_loss: 0.3270
Epoch 60/100
504/504 [==============================] - 0s 401us/step - loss: 0.3022 - val_loss: 0.3235
Epoch 61/100
504/504 [==============================] - 0s 393us/step - loss: 0.2990 - val_loss: 0.3206
Epoch 62/100
504/504 [==============================] - 0s 467us/step - loss: 0.2958 - val_loss: 0.3193
Epoch 63/100
504/504 [==============================] - 0s 444us/step - loss: 0.2924 - val_loss: 0.3155
Epoch 64/100
504/504 [==============================] - 0s 391us/step - loss: 0.2896 - val_loss: 0.3117
Epoch 65/100
504/504 [==============================] - 0s 390us/step - loss: 0.2861 - val_loss: 0.3087
Epoch 66/100
504/504 [==============================] - 0s 389us/step - loss: 0.2831 - val_loss: 0.3062
Epoch 67/100
504/504 [==============================] - 0s 408us/step - loss: 0.2798 - val_loss: 0.3030
Epoch 68/100
504/504 [==============================] - 0s 443us/step - loss: 0.2766 - val_loss: 0.3003
Epoch 69/100
504/504 [==============================] - 0s 389us/step - loss: 0.2734 - val_loss: 0.2977
Epoch 70/100
504/504 [==============================] - 0s 364us/step - loss: 0.2705 - val_loss: 0.2943
Epoch 71/100
504/504 [==============================] - 0s 330us/step - loss: 0.2672 - val_loss: 0.2912
Epoch 72/100
504/504 [==============================] - 0s 364us/step - loss: 0.2654 - val_loss: 0.2864
Epoch 73/100
504/504 [==============================] - 0s 399us/step - loss: 0.2611 - val_loss: 0.2849
Epoch 74/100
504/504 [==============================] - 0s 431us/step - loss: 0.2583 - val_loss: 0.2816
Epoch 75/100
504/504 [==============================] - 0s 357us/step - loss: 0.2553 - val_loss: 0.2783
Epoch 76/100
504/504 [==============================] - 0s 348us/step - loss: 0.2529 - val_loss: 0.2761
Epoch 77/100
504/504 [==============================] - 0s 355us/step - loss: 0.2507 - val_loss: 0.2711
Epoch 78/100
504/504 [==============================] - 0s 363us/step - loss: 0.2471 - val_loss: 0.2681
Epoch 79/100
504/504 [==============================] - 0s 396us/step - loss: 0.2448 - val_loss: 0.2661
Epoch 80/100
504/504 [==============================] - 0s 425us/step - loss: 0.2407 - val_loss: 0.2631
Epoch 81/100
504/504 [==============================] - 0s 434us/step - loss: 0.2378 - val_loss: 0.2613
Epoch 82/100
504/504 [==============================] - 0s 359us/step - loss: 0.2348 - val_loss: 0.2562
Epoch 83/100
504/504 [==============================] - 0s 359us/step - loss: 0.2324 - val_loss: 0.2536
Epoch 84/100
504/504 [==============================] - 0s 432us/step - loss: 0.2300 - val_loss: 0.2514
Epoch 85/100
504/504 [==============================] - 0s 392us/step - loss: 0.2278 - val_loss: 0.2495
Epoch 86/100
504/504 [==============================] - 0s 359us/step - loss: 0.2256 - val_loss: 0.2473
Epoch 87/100
504/504 [==============================] - 0s 321us/step - loss: 0.2234 - val_loss: 0.2447
Epoch 88/100
504/504 [==============================] - 0s 386us/step - loss: 0.2210 - val_loss: 0.2436
Epoch 89/100
504/504 [==============================] - 0s 351us/step - loss: 0.2194 - val_loss: 0.2420
Epoch 90/100
504/504 [==============================] - 0s 327us/step - loss: 0.2179 - val_loss: 0.2385
Epoch 91/100
504/504 [==============================] - 0s 364us/step - loss: 0.2160 - val_loss: 0.2375
Epoch 92/100
504/504 [==============================] - 0s 396us/step - loss: 0.2142 - val_loss: 0.2357
Epoch 93/100
504/504 [==============================] - 0s 392us/step - loss: 0.2116 - val_loss: 0.2331
Epoch 94/100
504/504 [==============================] - 0s 354us/step - loss: 0.2104 - val_loss: 0.2305
Epoch 95/100
504/504 [==============================] - 0s 350us/step - loss: 0.2084 - val_loss: 0.2286
Epoch 96/100
504/504 [==============================] - 0s 357us/step - loss: 0.2075 - val_loss: 0.2279
Epoch 97/100
504/504 [==============================] - 0s 393us/step - loss: 0.2060 - val_loss: 0.2250
Epoch 98/100
504/504 [==============================] - 0s 435us/step - loss: 0.2047 - val_loss: 0.2243
Epoch 99/100
504/504 [==============================] - 0s 469us/step - loss: 0.2030 - val_loss: 0.2214
Epoch 100/100
504/504 [==============================] - 0s 757us/step - loss: 0.2024 - val_loss: 0.2210

In [18]:
from sklearn import metrics
import numpy as np
target_pred = model.predict(predictors_test_norm)
mserrC = metrics.mean_squared_error(target_test_norm, target_pred)
r2_scoresC = metrics.r2_scores = metrics.r2_score(target_test_norm, target_pred)
print('mserrA: {:.2f}'.format(mserrC))
print('mse_StdDev: {:.2f}'.format(r2_scoresC))
print('R^2_Mean: {:.2f}'.format(np.mean(r2_scoresC)))
print('R^2_StdDev: {:.2f}'.format(np.std(r2_scoresC)))

mserrA: 0.21
mse_StdDev: 0.79
R^2_Mean: 0.79
R^2_StdDev: 0.00